name: build
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        mkdir -p ~/.local/bin
        cd ~/.local/bin

        curl https://zyedidia.github.io/eget.sh | sh

        ./eget xnuk/swc-minifier -t 0.2.2
        ./eget WebAssembly/binaryen -t version_114 --file=wasm-opt

        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - run: corepack enable
    - run: pnpm install --frozen-lockfile

    - run: rustup default stable
    - run: rustup target add wasm32-unknown-unknown

    - run: pnpm xtask:setup
    - run: pnpm wasm:build
    - run: pnpm web:build

    - run: >
        swc-minifier --config=swc-minifier.json dist/web/index.js > dist/web/index.min.js &&
        mv dist/web/index.min.js dist/web/index.js

    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist/web/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v1
      id: deployment
