name: build
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: cache/bin-cache/
        key: ${{ runner.os }}-binaries-${{ hashFiles('download-linux-x64.sh') }}
    - uses: actions/cache@v3
      with:
        path: cache/deno/
        key: ${{ runner.os }}-deno-cache-${{ hashFiles('js/deno.lock') }}
    - uses: actions/cache@v3
      with:
        path: |
          cache/rust/
          ~/.rustup/
          ~/.cargo/
        key: ${{ runner.os }}-cargo-cache-${{ hashFiles('rust/Cargo.lock') }}
    - run: rustup default stable
    - run: rustup target add wasm32-unknown-unknown
    - run: make
    - uses: actions/upload-pages-artifact@v1
      with:
        path: cache/js/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/deploy-pages@v1
      id: deployment
